const values=['Kindness','Courage','Curiosity','Independence','Creativity','Responsibility','Cooperation','Resilience'];
const valuesEl=document.querySelector('#values'); const selected=new Set(['Kindness','Curiosity']);
values.forEach(v=>{const b=document.createElement('button');b.className='chip'+(selected.has(v)?' active':'');b.textContent=v;b.onclick=()=>{selected.has(v)?selected.delete(v):selected.add(v);b.classList.toggle('active')};valuesEl.appendChild(b)});
const $=id=>document.getElementById(id); const status=$('status');
const saved=JSON.parse(localStorage.getItem('moonbeamStories')||'[]'); renderLibrary();
$('generate').onclick=async()=>{const child={name:$('name').value.trim(),age:Number($('age').value),interests:$('interests').value.trim(),dislikes:$('dislikes').value.trim(),length:$('length').value,tone:$('tone').value,values:[...selected]};if(!child.name){status.textContent='Give me a name or nickname first.';return}status.textContent='Writing tonight’s adventure…';$('generate').disabled=true;try{const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({child})});const data=await r.json();if(!r.ok)throw Error(data.error);renderStory(data.story,data.image,child)}catch(e){status.innerHTML='<span class="error">'+escapeHtml(e.message)+'</span>'}finally{$('generate').disabled=false}};
function renderStory(s,image,child){status.textContent='';const el=$('story');el.classList.remove('hidden');el.innerHTML=(image?`<img class="hero" src="${image}">`:'')+`<h1>${escapeHtml(s.title)}</h1><p class="page">${escapeHtml(s.opening)}</p>`+(s.pages||[]).map(p=>`<article class="page">${escapeHtml(p.text)}</article>`).join('')+`<p class="closing">${escapeHtml(s.closing)}</p><div class="actions"><button class="secondary" id="save">♡ Save story</button><button class="secondary" onclick="window.scrollTo({top:0,behavior:'smooth'})">↟ New story</button></div>`;document.getElementById('save').onclick=()=>{saved.unshift({title:s.title,story:s,image,child,at:new Date().toISOString()});saved.splice(12);localStorage.setItem('moonbeamStories',JSON.stringify(saved));renderLibrary();document.getElementById('save').textContent='♥ Saved'};el.scrollIntoView({behavior:'smooth'})}
function renderLibrary(){const l=$('library');if(!saved.length){l.innerHTML='<p class="muted">Your saved stories will appear here.</p>';return}l.innerHTML=saved.map((x,i)=>`<button onclick="openSaved(${i})">📖 ${escapeHtml(x.title)} <small>— ${escapeHtml(x.child.name)}</small></button>`).join('')}
window.openSaved=i=>{const x=saved[i];renderStory(x.story,x.image,x.child)};function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
