-- Moonbeam Stories V52 — one introductory trial per device and per network in 30 days.
-- Run ONCE in Supabase > SQL Editor BEFORE deploying V52.

create table if not exists public.trial_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_hash text not null unique,
  network_hash text,
  claimed_at timestamptz not null default now()
);
create index if not exists trial_claims_network_idx on public.trial_claims(network_hash, claimed_at desc);
alter table public.trial_claims enable row level security;
grant select, insert on table public.trial_claims to service_role;
grant usage, select on sequence public.trial_claims_id_seq to service_role;

-- Future accounts start at zero. Their three introductory credits are granted only
-- after the verified account successfully claims the trial for this device.
create or replace function public.give_new_user_story_credits()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.story_credits (user_id, balance, lifetime_granted, lifetime_spent)
  values (new.id, 0, 0, 0)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

-- Claim three introductory credits atomically. One device can claim once.
-- A network may claim the introductory offer only once in any rolling 30-day period.
-- An advisory transaction lock serialises simultaneous claims from the same network.
create or replace function public.claim_intro_trial(p_user_id uuid, p_device_hash text, p_network_hash text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance integer;
  v_granted integer;
  v_network_claims integer;
begin
  select balance, lifetime_granted into v_balance, v_granted
  from public.story_credits where user_id = p_user_id for update;

  if v_balance is null then
    insert into public.story_credits(user_id,balance,lifetime_granted,lifetime_spent)
    values(p_user_id,0,0,0) on conflict(user_id) do nothing;
    select balance, lifetime_granted into v_balance, v_granted
    from public.story_credits where user_id = p_user_id for update;
  end if;

  -- Existing/test accounts that already received credits are left untouched.
  if coalesce(v_granted,0) > 0 then
    return jsonb_build_object('granted',false,'reason','already_granted','balance',v_balance);
  end if;

  if exists(select 1 from public.trial_claims where device_hash = p_device_hash) then
    return jsonb_build_object('granted',false,'reason','device_used','balance',v_balance);
  end if;

  if p_network_hash is not null and p_network_hash <> '' then
    -- Prevent two simultaneous sign-ups from both passing the count check.
    perform pg_advisory_xact_lock(hashtext(p_network_hash));
    select count(*) into v_network_claims from public.trial_claims
    where network_hash = p_network_hash and claimed_at > now() - interval '30 days';
    if v_network_claims >= 1 then
      return jsonb_build_object('granted',false,'reason','network_limit','balance',v_balance);
    end if;
  end if;

  begin
    insert into public.trial_claims(user_id,device_hash,network_hash)
    values(p_user_id,p_device_hash,nullif(p_network_hash,''));
  exception when unique_violation then
    return jsonb_build_object('granted',false,'reason','device_used','balance',v_balance);
  end;

  update public.story_credits
  set balance = balance + 3,
      lifetime_granted = lifetime_granted + 3,
      updated_at = now()
  where user_id = p_user_id
  returning balance into v_balance;

  return jsonb_build_object('granted',true,'reason','intro_trial','balance',v_balance);
end;
$$;

revoke all on function public.claim_intro_trial(uuid,text,text) from public, anon, authenticated;
grant execute on function public.claim_intro_trial(uuid,text,text) to service_role;
