-- Moonbeam Stories V53 — Stripe credit purchases.
-- Run ONCE in Supabase > SQL Editor BEFORE deploying V53.
-- This does not reset existing balances or trial claims.

alter table public.story_credits
add column if not exists lifetime_purchased integer not null default 0 check (lifetime_purchased >= 0);

create table if not exists public.story_credit_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  stripe_checkout_session_id text not null unique,
  stripe_payment_intent_id text,
  stripe_event_id text,
  credits integer not null check (credits > 0),
  amount_total integer not null check (amount_total >= 0),
  currency text not null default 'gbp',
  created_at timestamptz not null default now(),
  fulfilled_at timestamptz not null default now()
);

create index if not exists story_credit_purchases_user_idx
on public.story_credit_purchases(user_id, fulfilled_at desc);

alter table public.story_credit_purchases enable row level security;

drop policy if exists "Users can read own credit purchases" on public.story_credit_purchases;
create policy "Users can read own credit purchases"
on public.story_credit_purchases for select
to authenticated
using (auth.uid() = user_id);

grant select on table public.story_credit_purchases to authenticated;
grant select, insert on table public.story_credit_purchases to service_role;
grant usage, select on sequence public.story_credit_purchases_id_seq to service_role;

-- Fulfil a paid Stripe Checkout Session exactly once.
-- The price/credit pairs are validated again inside Postgres so a malformed
-- server request cannot mint an arbitrary number of credits.
create or replace function public.fulfill_story_credit_purchase(
  p_user_id uuid,
  p_session_id text,
  p_payment_intent_id text,
  p_credits integer,
  p_amount_total integer,
  p_currency text,
  p_event_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_purchase_id bigint;
  v_balance integer;
  v_currency text := lower(coalesce(p_currency,''));
begin
  if p_session_id is null or length(trim(p_session_id)) < 8 then
    raise exception 'Invalid checkout session';
  end if;

  if v_currency <> 'gbp' then
    raise exception 'Unexpected payment currency';
  end if;

  if not (
    (p_credits = 10 and p_amount_total = 999) or
    (p_credits = 25 and p_amount_total = 1999) or
    (p_credits = 50 and p_amount_total = 3499)
  ) then
    raise exception 'Unexpected credit pack or amount';
  end if;

  -- The unique Stripe Checkout Session ID is the idempotency key. Only the
  -- request that successfully inserts this row is allowed to grant credits.
  insert into public.story_credit_purchases(
    user_id, stripe_checkout_session_id, stripe_payment_intent_id,
    stripe_event_id, credits, amount_total, currency
  ) values (
    p_user_id, trim(p_session_id), nullif(trim(coalesce(p_payment_intent_id,'')),''),
    nullif(trim(coalesce(p_event_id,'')),''), p_credits, p_amount_total, v_currency
  )
  on conflict (stripe_checkout_session_id) do nothing
  returning id into v_purchase_id;

  if v_purchase_id is null then
    select balance into v_balance from public.story_credits where user_id = p_user_id;
    return jsonb_build_object('granted',false,'reason','already_fulfilled','balance',coalesce(v_balance,0));
  end if;

  insert into public.story_credits(user_id,balance,lifetime_granted,lifetime_spent,lifetime_purchased)
  values(p_user_id,0,0,0,0)
  on conflict(user_id) do nothing;

  update public.story_credits
  set balance = balance + p_credits,
      lifetime_granted = lifetime_granted + p_credits,
      lifetime_purchased = lifetime_purchased + p_credits,
      updated_at = now()
  where user_id = p_user_id
  returning balance into v_balance;

  return jsonb_build_object('granted',true,'reason','purchase','balance',v_balance,'credits',p_credits);
end;
$$;

revoke all on function public.fulfill_story_credit_purchase(uuid,text,text,integer,integer,text,text) from public, anon, authenticated;
grant execute on function public.fulfill_story_credit_purchase(uuid,text,text,integer,integer,text,text) to service_role;

-- V52 hardening follow-up: a missing credit row must start at zero, never
-- silently mint another three-credit trial. Trial credits are granted only by
-- claim_intro_trial().
create or replace function public.consume_story_credit(p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance integer;
begin
  select balance into v_balance
  from public.story_credits
  where user_id = p_user_id
  for update;

  if v_balance is null then
    insert into public.story_credits (user_id, balance, lifetime_granted, lifetime_spent, lifetime_purchased)
    values (p_user_id, 0, 0, 0, 0)
    on conflict (user_id) do nothing;
    select balance into v_balance from public.story_credits where user_id = p_user_id for update;
  end if;

  if coalesce(v_balance,0) <= 0 then
    return -1;
  end if;

  update public.story_credits
  set balance = balance - 1,
      lifetime_spent = lifetime_spent + 1,
      updated_at = now()
  where user_id = p_user_id
  returning balance into v_balance;

  return v_balance;
end;
$$;

revoke all on function public.consume_story_credit(uuid) from public, anon, authenticated;
grant execute on function public.consume_story_credit(uuid) to service_role;
